services:
  - type: web
    name: hcv-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        sync: false
